[project]
name = "super-res"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aim>=3.29.1",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "omegaconf>=2.3.0",
    "opencv-python>=4.11.0.86",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.0",
    "torch>=2.7.1",
    "torchsr>=1.0.4",
    "torchvision>=0.22.1",
    "tqdm>=4.67.1",
]


[dependency-groups]
dev = [
    "ruff>=0.12.3",
]

[tool.ruff]
target-version = "py311"
fix = true
lint.select = ["E", "F", "W", "I"]
lint.ignore = ["E501"]
line-length = 120
