debug: True
output_dir: ""
# python -m experiments.fsrcnn_finetune -m training.loss=mae,mse,sobel,fourier
training:
  device: "cuda"
  scale: 2
  max_epochs: 200
  patience: 20
  loss: "sobel" # "mae" | "mse" | "sobel" | "fourier" | "vgg_perceptual"
  use_scaling: False
  optimizer:
    type: "adamw" # "adamw" | "sgd"
    lr: 1e-4
    weight_decay: 1e-4
  scheduler:
    type: "cosine_annealing_warm_restarts"
    T_0: 25
    T_mult: 1
    eta_min: 1e-6
  loss_scales:
    mae: 0.00453282
    mse: 0.00007101
    sobel: 0.01959570
    fourier: 0.75516648
    vgg_perceptual: 0.73848135

train_dataloader:
  batch_size: 32
  shuffle: True
  num_workers: 8
  pin_memory: True
  prefetch_factor: 2
  persistent_workers: True
  multiprocessing_context: "spawn"

val_dataloader:
  batch_size: 32
  shuffle: False
  num_workers: 8
  pin_memory: True
  prefetch_factor: 2
  persistent_workers: True
  multiprocessing_context: "spawn"

test_dataloader:
  batch_size: 16
  shuffle: False
  num_workers: 16
  pin_memory: True
  prefetch_factor: 2
  persistent_workers: True
  multiprocessing_context: "spawn"

data:
  patch_size: 64
  train:
    x: "/tmp/data_sr/train/lr"
    y: "/tmp/data_sr/train/hr"
    pt_file: "tmp/data_sr/quake_dataset_train.pt"
  test:
    x: "data/test/lr"
    y: "data/test/hr"
  val:
    x: "/tmp/data/val/lr"
    y: "/tmp/data/val/hr"
    pt_file: "tmp/data_sr/quake_dataset_val.pt"
plotting:
  dir: "plots"

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S-%f}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S-%f}
    subdir: ${hydra.job.num}
