debug: True

training:
  device: 'cuda'
  scale: 2
  max_epochs: 100
  patience: 5
  optimizer:
    lr: 3e-4
    weight_decay: 1e-6
  scheduler:
    warmup_steps: 1000
    gamma: 0.5
    step_size: 10000
    

train_dataloader:
  batch_size: 16
  shuffle: True
  num_workers: 16
  pin_memory: True
  prefetch_factor: 2
  persistent_workers: True
  multiprocessing_context: "spawn"

val_dataloader:
  batch_size: 16
  shuffle: False
  num_workers: 16
  pin_memory: True
  prefetch_factor: 2
  persistent_workers: True
  multiprocessing_context: "spawn"

test_dataloader:
  batch_size: 16
  shuffle: False
  num_workers: 16
  pin_memory: True
  prefetch_factor: 2
  persistent_workers: True
  multiprocessing_context: "spawn"

data:
  train:
    x: '/mnt/local/rs/train/lr'
    x_4x: '/mnt/local/rs/train/lr_4x'
    y: '/mnt/local/rs/train/hr'
  test:
    x: '/mnt/local/rs/test/lr'
    x_4x: '/mnt/local/rs/test/lr_4x'
    y: '/mnt/local/rs/test/hr'
  val:
    x: '/mnt/local/rs/val/lr'
    x_4x: '/mnt/local/rs/val/lr_4x'
    y: '/mnt/local/rs/val/hr'


plotting:
  dir: 'plots'